### ISSUE TITLE
Hand calibration

### ISSUE THREAD

**Issue by missxa** [Adjuvo/SenseGlove-API#1]
Are you planning to add functions for calibration, similar to Unity API [here](https://github.com/Adjuvo/SenseGlove-Unity/wiki/Calibration)?

**Comment by MaxLammers** [comment]
We are indeed planning to add calibration functionality: A technical implementation in the SGCore API, and a guided implementation of said functions integrated into SenseCom.

We are currently improving our tracking algorithms, and will integrate proper calibration in both the Unity /C# and C++ API once this is finished. Expected to take about one month

**Comment by diarodriguezva** [comment]
We are also interested in the calibration functions, any update ?

**Comment by MaxLammers** [comment]
Update for those interested: We have a working new solver, and are currently implementing a guided hand calibration into _SenseCom_. At the moment, data will be stored on disk ("my documents/SenseGlove/Calibration/"). Will work on adding User Profiles after this update.
