### ISSUE TITLE
Does the API have the function of controlling the position of DK1?

### ISSUE THREAD

**Issue by yu-mei** [Adjuvo/SenseGlove-API#11]
Hello @MaxLammers,

I want to use the cable to drive the finger to the desired position. But I just found the mode of buzz and FFB in the API, does API have the function of position control (one direction is fine)?  And my understanding of DK1's FFB is generating the force to prevent the hands from closing, is it right?

Hope to receive your reply, thanks so much.

**Comment by MaxLammers** [comment]
Dear Yu-Mei,

The SenseGlove DK1 does not actively pull on the cables; it exerts a braking force on the cable to prevent the hands from closing. You can control what braking force is applies, but driving the finger to a desired position is not possible. 
Position control for the braking system (activating the brakes at a certain flexion / position) is not supported by the C++/C# API. You will need to implement such a system yourself. 
However, a rudimentary system based on physics engine collision has been implemented in [our Unity Plugin](https://github.com/Adjuvo/SenseGlove-Unity), which you might be able to use for inspiration. 

-Max

**Comment by yu-mei** [comment]
Thanks for quick reply, @MaxLammers. 

And I have another question that, I ran [SGCoreCpp_TestProgram.cpp](https://github.com/Adjuvo/SenseGlove-API/blob/master/Core/SGCoreCpp/examples/SGCoreCpp_TestProgram.cpp) and result is shown in below image. 

![result](https://user-images.githubusercontent.com/53110134/131523114-8f09abad-7131-466c-9531-b4b36317e8ac.png)

Questions:
1. handpose.ToString(): How could I get the value of each variable directly(e.g. CMC Abd MCP Abd)? I search the function in API but I can not figure it out. Should I need to process the output string? Obviously, the handAngle and jointRotation in class handpose is not what I need because of their multiple dimensions.
2. What is the dimension of the CMC Abd for example, is it degree(°) in physics? And What is the relative value and positive direction of each, I did not find the illustration about it.
3. For the last output, Serialization Example, does it mean that it shows the default handpose on the disk?

**Comment by MaxLammers** [comment]
**1 & 2**
The ToString() function is there to print out the angles for easy reading on a console. The `handAngles` variable in the [`HandPose`](https://github.com/Adjuvo/SenseGlove-API/blob/master/Core/SGCoreCpp/incl/HandPose.h) contains the 'articulation angles' of the fingers that you are looking for, as an x, y, z (Pronation, Flexion, Abduction) vector (`Vect3D`) for each finger joint. `handAngle` values are given in radians, relative to the previous joint,  following the notation below:

![Coordinate System](https://user-images.githubusercontent.com/18416131/131631697-ebd58273-c5a8-4ddb-97de-c605b0b4e57e.png)

Unfortunately, I don't yet have a "get angle by anatomical notation" function, though that is a great idea for the next update. Instead, I'll give you the implementation of the HandPose.ToString() function for reference:
```
std::string HandPose::ToString(bool shortFormat)
{
	std::string res = "";
	for (int f = 0; f < handAngles.size(); f++)
	{
		if (handAngles[f].size() > 2)
		{
			//first joint.
			res += Util::StrStuff::ToString((SGCore::Finger)f) + ":\t";
			std::string abd = SGCore::Util::StrStuff::RoundedDegrees(handAngles[f][0].z);
			std::string f1  = SGCore::Util::StrStuff::RoundedDegrees(handAngles[f][0].y);
			std::string f2  = SGCore::Util::StrStuff::RoundedDegrees(handAngles[f][1].y);
			std::string f3  = SGCore::Util::StrStuff::RoundedDegrees(handAngles[f][2].y);
			if (f == 0)
			{
				std::string tw = std::to_string((int)(handAngles[f][0].x * Kinematics::Values::Rad2Deg));
				res += "CMC-Abd: " + abd + ",\tCMC-Tw: " + tw + ",\tCMC-Flx: " + f1 + ",\tMCP-Flx: " + f2 + ",\tIP-Flx: " + f3;
			}
			else
			{
				res += "MCP-Abd: " + abd + ",\tMCP-Flx: " + f1 + ",\tPIP-Flx: " + f2 + ",\tDIP-Flx: " + f3;
			}
			if (f < handAngles.size() - 1) { res += "\n"; }
			}
		}
		return res;
	}
}
```

**3**
The serialization is part of the test program, the source code of which is [in the examples folder](https://github.com/Adjuvo/SenseGlove-API/blob/master/Core/SGCoreCpp/examples/SGCoreCpp_TestProgram.cpp). We show how to generate a 'default' (hardcoded) HandPose and how to prepare it to be stored on disk (Serialization). We also deserialize it (as through we read it from disk), and compare the two for any inconsistencies.

**4**
Yes, the SenseGlove Sensor Data consists of 20 rotations - 4 per finger, representing the angles between each linkage - and the IMU data. The rotations are given in radians, and follow a similar notation to the handAngles.

**Comment by yu-mei** [comment]
Thank you @MaxLammers, your answer is very detailed and helpful.
