### ISSUE TITLE
What do the exclamation marks mean in the GUI ?

### ISSUE THREAD

**Issue by KeepThisTicket** [Adjuvo/SenseGlove-API#2]
Hi,

My sensecom GUI shows the two gloves (the two hands turn solid blue), but there is an exclamation mark beside each one. I can run the example fine so just wondering what those indicate ?

**Comment by fahdovski003** [comment]
![image](https://user-images.githubusercontent.com/37941505/91446774-e1fc0980-e845-11ea-9a67-62652420cb46.png)
