### ISSUE TITLE
How to create and setup Hand Profile ?

### ISSUE THREAD

**Issue by KeepThisTicket** [Adjuvo/SenseGlove-API#4]
How do we create hand profiles ? Can you explain what parameters the hand profile is composed of ? As far as I can tell it indicates Left/Right, and also specifies the finger segment lengths - is this correct ?

The specific section of code I'm referring to is shown below from SGCoreCpp_Example.cpp, where it mentions hand profiles.

```
//If we wish to calculate hand variables, we need a "hand profile" to tell the Sense Glove our hand lengths.
                    SGCore::SG::SG_HandProfile handProfile = SGCore::SG::SG_HandProfile::Default(testGlove.IsRight()); //create a default profile, either left or right.
                    SGCore::Kinematics::BasicHandModel handModel = SGCore::Kinematics::BasicHandModel::Default(testGlove.IsRight()); //create a default profile, either left or right.
                    std::vector<SGCore::Kinematics::Vect3D> tipPositions = glovePose.CalculateFingerTips(handProfile); //calculates fingertip position
```

**Comment by MaxLammers** [comment]
I'm assuming you're using the latest version of our Core API. Its example code is a little bit unclear, and also a little outdated. I will update it to better reflect what is happening.

The current implementation of the C++ API contains only a solver based on sensor angle interpolation. To generate a `HandPose`, the SenseGlove needs to know two things; a set of Interpolation Values to calculate joint angles, contained within the `SGCore::SG::SG_HandProfile` object, and the geometry of the hand to calculate joints positions, which is contained within the `SGCore::Kinematics::BasicHandModel` class. The `BasicHandModel` used to be directly integrated into the `SG_HandProfile` class, but was separated to allow one to calculate with varying hand sizes for the same user.

There is a class documentation available for the SG_HandProfile class, which tells you all of its parameters and how to construct it. If you have the Core/SGCoreCpp/doc folder on your system, you can find the class documentation by either opening the `Core/SGCoreCpp/doc/class_s_g_core_1_1_s_g_1_1_s_g___hand_profile.html` or by opening the `Core/SGCoreCpp/doc/index.html` and searching for it. The same goes for the `SG_BasicHandModel`. Each method can also direct you to the class reference of any non-standard parameters.

If you want a baseline from which to work, the `SGCore::SG::SG_HandProfile::Default(bool rightHand)` and/or `SGCore::Kinematics::BasicHandModel::Default(bool rightHand)` will generate some base values which you can tweak or modify to suit your needs. Tweaking the handprofile will change which joint angles are calculated, while changing the basicHandModel will affect the joint positions and fingertip distance.

In the current version of our C++ API, each SenseGlove keeps track of its minimum and maximum sensor values, which are used as an input for the interpolation values of the hand (contained within `SGCore::Kinematics::HandInterpolator`). You can apply these values to the SG_HandProfile through the `void ApplyCalibration(SG_HandProfile& profile)` method of the `SenseGlove` class.

**Comment by fahdovski003** [comment]
@MaxLammers  Can you provide a snippet code in C++ to do this please ?

**Comment by MaxLammers** [comment]
I'm assuming you're referring to this particular section:
> In the current version of our C++ API, each SenseGlove keeps track of its minimum and maximum sensor values, which are used as an input for the interpolation values of the hand (contained within `SGCore::Kinematics::HandInterpolator`). You can apply these values to the `SG_HandProfile` through the void `ApplyCalibration(SG_HandProfile& profile)` method of the `SenseGlove` class.

One important detail is that, while sensor data comes in via the SGConnect library, it is parsed & converted by the SGCore library: We don't access the incoming data until you call the  `UpdateCalibrationRange()` function. This function is automatically called within the GetSensorData, GetGlovePose, and GetHandPose functions, since these all rely on parsing sensor data.

The following code should run you through the calibration process:
```
int main()
{
	std::cout << "Testing SGCore C++ Library - Calibration"<< std::endl;
	std::cout << "=======================================" << std::endl;

	if (SGCore::DeviceList::SenseCommRunning()) //check if the Sense Comm is running. If not, warn the end user.
	{
		SGCore::SG::SenseGlove testGlove;
		if (SGCore::SG::SenseGlove::GetSenseGlove(testGlove)) //retrieves the first Sense Glove it can find. Returns true if one can be found
		{
			std::cout << "Connected to a " << (testGlove.IsRight() ? "right" : "left") << "-handed SenseGlove. Staring calibration" << std::endl;

			/* 
			Our goal is to find the min / max sensor values, which correspond to the user opening their hand and making a fist.
			We can only update this range after parsing sensor data, which happens when accessing sensorData, glovePoses or handPoses.
			In our VR use cases, we pull new hand data each frame, and so this min/max range is updated automatically. 
			In this example, we will update the range twice; once when the hand is 'open', once when it is closed into a fist.
			*/ 		

			// Step 1: Open hand - Calibrates extension
			std::cout << std::endl;
			std::cout << "Step 1: Place your hand on a flat surface, like a table, and spread your thumb and fingers." << std::endl;
			// Once you get the hang of this motion, you can do it without the surface.
			std::cout << "Once your hand is in the right position, press any key to continue" << std::endl; 
			system("pause");
			
			// This function updates the calibration range of testGlove.
			testGlove.UpdateCalibrationRange(); // Instead of this method, you can also use the GetSensorData(), GetGlovePose() or GetHandPose function instead.


			// Step 2: Fist - Calibrates flexion
			std::cout << std::endl;
			std::cout << "Step 2: Close your hand into a fist. Make sure your fingers aren't wrapped around your thumb." << std::endl;
			std::cout << "Once your hand is in the right position, press any key to continue" << std::endl;
			system("pause");

			// This function updates the calibration range of testGlove. 
			testGlove.UpdateCalibrationRange();


			// At this point, we've collected data while the hand was open, and when it was closed. 
			// The calibration range should now have the two extremes to interpolate between.
			// Let's check & ouput the ranges:
			std::vector<SGCore::Kinematics::Vect3D> minRanges, maxRanges;
			testGlove.GetCalibrationRange(minRanges, maxRanges);
			
			// The calibration ranges contain the x, y, z values, which represent the pronation/supination, flexion/extension, and abduction/adduction movements respectively, in radians. 
			// For readability's sake, we'll print out the flexion/extension values in degrees.
			float rad2Deg = 180 / M_PI;
			std::cout << std::endl << "Evaluated the following calibration range for extension/flexion" << std::endl;
			std::cout << "Extensions: ";
			for (int f = 0; f < minRanges.size(); f++)
			{
				std::cout << std::to_string((int)(rad2Deg * minRanges[f].y));
				if (f < minRanges.size() - 1) { std::cout << ", "; }
			}
			std::cout << std::endl << "Flexions: ";
			for (int f = 0; f < maxRanges.size(); f++)
			{
				std::cout << std::to_string((int)(rad2Deg * maxRanges[f].y));
				if (f < maxRanges.size() - 1) { std::cout << ", "; }
			}
			std::cout << std::endl;

			// Now we apply the calibration to a default profile
			SGCore::HandProfile cachedProfile = SGCore::HandProfile::Default( testGlove.IsRight() ); //a default profile for the right-sided glove.
			testGlove.ApplyCalibration(cachedProfile);

			// And can now use it to calculate handPoses
			SGCore::HandPose handPose;
			if (testGlove.GetHandPose(cachedProfile, handPose))
			{
				std::cout << std::endl << "With these ranges, we've calculated the following hand angles:" << std::endl;
				std::cout << handPose.ToString() << std::endl;
			}
			else
			{
				std::cout << "Something went wrong while trying to calucate a handPose. Perhaps a packet was dropped or an exception occurs." << std::endl;
			}
			
			// Finally, we can store the profile in its serialized form to use later
			std::string serializedProfile = cachedProfile.Serialize();

			// And Deserialize it back into a useable profile
			SGCore::HandProfile loadedProfile = SGCore::HandProfile::Deserialize(serializedProfile);

		}
	}
	else
		std::cout << "SenseComm is not running. Please start it and try again." << std::endl;

	std::cout << "=======================================" << std::endl;
	std::cout << "Press any key to exit." << std::endl;
	system("pause");
}
```

**Comment by fahdovski003** [comment]
I could not find the function testGlove.GetCalibrationRange(minRanges, maxRanges);

**Comment by fahdovski003** [comment]
Is there a calibration sample code for the `SG_BasicHandModel` too ?

**Comment by MaxLammers** [comment]
> hi @MaxLammers , thank you for the sample code. However, I could not find the function `testGlove.GetCalibrationRange(minRanges, maxRanges);`

My apologies, the `testGlove.GetCalibrationRange(minRanges, maxRanges);` function was not yet updated on the repository. I've updated the C++ Core API to include said function, as well as the example code posted above. The example code should still compile and calibrate if you comment out the section where we print the calibration range to the console.

**Comment by MaxLammers** [comment]
> Is there a calibration sample code for the `SGCore::Kinematics::BasicHandModel` too ?

Unfortunately, there is no calibration for the `SGCore::Kinematics::BasicHandModel` available yet. You will have to manually input the hand geometry of your user, or use the default values. Changing the BasicHandModel will affect the joint positions and fingertip distance. If you're mainly interested in joint rotations, you can get away with the default model, since the current solvers do not depend on the finger lengths for that.

**Comment by fahdovski003** [comment]
@MaxLammers  Thanks.

**Comment by huudatnguyen** [comment]
Hi, 

Im testing the UE4 Demo. I have everything branched with the Github and SenseCom is running. However i'm having problems with the "SenseGloveAnimInstance", the skeletal mesh animation is tripping and it's not in sinc with the hand motion. My sense is that's the C++ code of the animation is bugging or not well calibrated. How can I solve this?
