### ISSUE TITLE
SendHaptics with thumperCmd

### ISSUE THREAD

**Issue by Ecenys** [Adjuvo/SenseGlove-API#8]
Hello,

@MaxLammers 

I tried to use the instruction "SendHaptics(SGCore::Haptics::ThumperCmd)" in the API (it appears in the doc, image 1), but visual notifies me as an error (image 2).

I think the problem is that this instruction is not in the .h file (image 3).

---------------------------------------------------
Image 1:
![imagen](https://user-images.githubusercontent.com/27973600/107449636-2f460c00-6b44-11eb-890a-774955d8675c.png)

---------------------------------------------------
Image 2:
![imagen](https://user-images.githubusercontent.com/27973600/107449212-7253af80-6b43-11eb-854e-d52328dbfd44.png)

---------------------------------------------------
Image 3:
![image3](https://user-images.githubusercontent.com/27973600/107449438-da09fa80-6b43-11eb-81bc-276e93b94d4f.PNG)

**Comment by MaxLammers** [comment]
Dear Oscar,

Image 1 shows the documentation of a different kind of HapticGlove; "Fino", while image 3 is a screenshot of the "SenseGlove" header file. While both of these are HapticGloves, they have a very different implementation when it comes to their "thumper" (wrist haptics). The DK1 SenseGlove does not allow for direct control over the Thumper amplitude. Instead you send a command that activates one of 9 effects that are hard-coded in the driver circuit on the glove. While the SenseGlove class does override a SendHaptics function, as seen at the bottom of image 3, it cannot do anything with the ThumperCmd.

Based on the error with the ThumperCmd argument, I'm assuming your _rightGlove_ in image 2 is a _SenseGlove_ object. In that case, you'll need to send a _SG_ThumperCmd_ - an enumerator describing one of the 9 hard-coded waveforms.
