### ISSUE TITLE
Tag releases using git tag and GitHub Releases? 

### ISSUE THREAD

**Issue by traversaro** [Adjuvo/SenseGlove-API#9]
Hi @MaxLammers, thanks a lot for all the hard work! 

I saw that you recently add a commit with an indication of a release (see https://github.com/Adjuvo/SenseGlove-API/commit/baad587d4e165d7bfafd7f0c8ee6a1ce8ad651d6). While it is possible to always recover that commit from its hash, it may be convenient if you could release a GitHub release with a descriptive tag name (for example `v1.3`) using the [GitHub Releases](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository). 

In this way, it would be more clear which commits correspond to a release, and specifically which commit corresponds to a release.

Thanks a lot in advance.

**Comment by MaxLammers** [comment]
Dear @traversaro,

That sounds easy enough to set up, I'll get on it for this version and the upcoming ones.

**Comment by traversaro** [comment]
Thanks @MaxLammers, I already saw the first release in https://github.com/Adjuvo/SenseGlove-API/releases/tag/v1.3.1 , so I think I can close the issue.

**Comment by MaxLammers** [comment]
You're faster than I am ;)
Added Release Tag for the latest release, `v1.3.1` for your convenience

**Comment by traversaro** [comment]
fyi @kouroshD @S-Dafarra @lrapetti

**Comment by traversaro** [comment]
> You're faster than I am ;)

Just luck, I happened to check the repo right when you did the release. : ) Thanks again!
